FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

COPY package.json /app/

COPY frontend/package.json /app/frontend/

WORKDIR /app/frontend

RUN npm install

COPY ./frontend /app/frontend

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
